swaggerSetup:
  endpointOverride: "localhost"
  #endpointOverride: "localhost:80"

apiInfoData:
  apiVersion: 1.0.0
  title: "Feeds API Server"
  description: "Demo of User Feeds Application"
  termsOfServiceUrl: "None"
  contact: "sndshd@gmail.com"
  license: "CC0 1.0 Universal"
  licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/"

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 10991
  requestLog:
    timeZone: UTC
    appenders:
     - type: file
       currentLogFilename: var/output/logs/access.log 
       threshold: ALL
       archive: true
       archivedLogFilenamePattern: var/output/logs/access.%d{yyyy-MM-dd-HH}.log 
       archivedFileCount: 24
       timeZone: UTC

requestTracing:
    requestIdContext: "feeds"
    enableLogging: false

metrics:
  reporters:
    - type: log
      frequency: 10 seconds
      logger: "org.sectorzero.feeds.metrics"
      durationUnit: milliseconds
      rateUnit: seconds
